### PR TITLE
support v3.0.0.19

### PR DESCRIPTION
**Pull request by zabio3**
Congratulations on the release of the new version 🎉 

I'm also very happy to add the new features I've requested.

 - https://github.com/jiangwenyuan/nuster/issues/16

Updated Dockerfile for new Nustar version. If there are no problems, I would be happy to update Dockerhub and incorporate it :)

### CODE REVIEW

**Comment by jiangwenyuan** [comment]
Hi, thank you so much, let me see how to add collaborator on docker hub

**Comment by zabio3** [comment]
> let me see how to add collaborator on docker hub

Does that mean we will add collaborators to docker hub?
Thank you. My dockerhub account.

 - https://hub.docker.com/u/zabio3

> Only the owner of the repository has administrative access.

> You can also assign more granular collaborator rights (“Read”, “Write”, or “Admin”) on Docker Hub by using organizations and teams.

 - https://docs.docker.com/docker-hub/repos/

**Comment by jiangwenyuan** [comment]
BTW, it's based on HAproxy v1.9 branch, so it should be H1.9

**Comment by zabio3** [comment]
> it's based on HAproxy v1.9 branch, so it should be H1.9

understood. Please wait for a while as we will issue a correction PR here.

**Pull request merged**
